-- Aura hardening + economy + social + notifications
-- Generated 2026-09-22. Apply through Supabase migrations before deploying the matching app code.

begin;

alter table public.profiles add column if not exists is_member boolean not null default false;
alter table public.profiles add column if not exists notify_new_posts boolean not null default true;
alter table public.profiles add column if not exists last_penalty_date date;
update public.profiles set is_member = true where is_member = false;

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_unique
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));

create table if not exists public.vote_events (
  id bigint generated by default as identity primary key,
  voter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint references public.posts(id) on delete cascade,
  source_type text not null check (source_type in ('post','profile','penalty')),
  old_value integer not null default 0,
  new_value integer not null default 0,
  delta numeric(12,1) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists vote_events_antiglaze_idx
  on public.vote_events (voter_id, target_user_id, created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null,
  post_id bigint references public.posts(id) on delete cascade,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);
create unique index if not exists notifications_post_once_idx
  on public.notifications(user_id, type, post_id, actor_id)
  where post_id is not null;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

create table if not exists public.weekly_rounds (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  winner_post_id bigint references public.posts(id) on delete set null,
  winner_user_id uuid references public.profiles(id) on delete set null,
  pool_amount numeric(12,1) not null default 0,
  settled_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists weekly_rounds_start_unique on public.weekly_rounds(starts_at);

insert into public.aura_ledger(user_id, amount, type, description, balance_after)
select p.id, 0, 'migration_reconcile', 'Ledger baseline after secure accounting migration', p.aura
from public.profiles p
where not exists (
  select 1 from public.aura_ledger l
  where l.user_id = p.id and l.type = 'migration_reconcile'
);

create or replace function public.is_aura_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and is_member = true
  );
$$;

create or replace function public.vote_cost(p_value integer)
returns numeric
language sql
immutable
as $$
  select case p_value
    when 1 then 1
    when 5 then 2
    when 10 then 5
    when 50 then 20
    else 0
  end::numeric;
$$;

create or replace function public.clown_tax_rate(p_balance numeric)
returns numeric
language sql
immutable
as $$
  select case
    when p_balance <= -500 then 0.50
    when p_balance <= -100 then 0.35
    when p_balance < 0 then 0.25
    else 0
  end::numeric;
$$;

create or replace function public.apply_aura_delta_internal(
  p_user_id uuid,
  p_delta numeric,
  p_type text,
  p_description text
)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current numeric;
  v_new numeric;
begin
  select aura into v_current from public.profiles where id = p_user_id for update;
  if not found then raise exception 'profile not found'; end if;

  v_new := round((coalesce(v_current,0) + p_delta)::numeric, 1);

  update public.profiles
  set aura = v_new,
      aura_all_time = greatest(coalesce(aura_all_time, 0), v_new)
  where id = p_user_id;

  insert into public.aura_ledger(user_id, amount, type, description, balance_after)
  values (p_user_id, round(p_delta::numeric,1), p_type, p_description, v_new);

  return v_new;
end;
$$;
revoke all on function public.apply_aura_delta_internal(uuid,numeric,text,text) from public, anon, authenticated;

create or replace function public.cast_post_vote(p_post_id bigint, p_value integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_owner uuid;
  v_old integer := 0;
  v_gain numeric;
  v_old_cost numeric;
  v_new_cost numeric;
  v_cost_delta numeric;
  v_owner_balance numeric;
  v_tax numeric := 0;
  v_owner_net numeric;
  v_new_owner numeric;
  v_new_voter numeric;
  v_tag_count integer := 0;
  v_tag record;
  v_tag_delta numeric;
  v_tag_balance numeric;
  v_tag_tax numeric;
  v_big_count integer;
begin
  if v_uid is null or not public.is_aura_member() then raise exception 'not authorized'; end if;
  if p_value not in (-50,-10,-5,-1,1,5,10,50) then raise exception 'invalid vote'; end if;

  select user_id into v_owner from public.posts where id = p_post_id for update;
  if not found then raise exception 'post not found'; end if;
  if v_owner = v_uid then raise exception 'cannot vote on your own post'; end if;

  select value into v_old from public.votes
  where voter_id = v_uid and post_id = p_post_id
  for update;
  if not found then v_old := 0; end if;
  if v_old = p_value then
    return jsonb_build_object('ok', true, 'unchanged', true);
  end if;

  if abs(p_value) = 50 then
    select count(*) into v_big_count
    from public.vote_events
    where voter_id = v_uid
      and target_user_id = v_owner
      and abs(new_value) = 50
      and source_type in ('post','profile')
      and created_at > now() - interval '24 hours';

    if v_big_count >= 3 then
      v_new_voter := public.apply_aura_delta_internal(
        v_uid, -50, 'anti_glaze', 'Too many ±50 votes to the same person in 24h'
      );
      insert into public.vote_events(voter_id,target_user_id,post_id,source_type,old_value,new_value,delta)
      values(v_uid,v_owner,p_post_id,'penalty',v_old,v_old,-50);
      return jsonb_build_object('ok', false, 'reason', 'anti_glaze', 'penalty', -50, 'voter_aura', v_new_voter);
    end if;
  end if;

  if v_old = 0 then
    insert into public.votes(voter_id, post_id, value) values(v_uid,p_post_id,p_value);
  else
    update public.votes set value = p_value where voter_id = v_uid and post_id = p_post_id;
  end if;

  v_gain := p_value - v_old;
  v_old_cost := public.vote_cost(v_old);
  v_new_cost := public.vote_cost(p_value);
  v_cost_delta := v_new_cost - v_old_cost;

  if v_cost_delta <> 0 then
    v_new_voter := public.apply_aura_delta_internal(
      v_uid, -v_cost_delta, 'vote_cost',
      case when v_cost_delta > 0 then 'Vote power cost' else 'Vote power refund' end
    );
  else
    select aura into v_new_voter from public.profiles where id = v_uid;
  end if;

  update public.posts set aura = round((coalesce(aura,0) + v_gain)::numeric,1) where id = p_post_id;

  select aura into v_owner_balance from public.profiles where id = v_owner for update;
  v_owner_net := v_gain;
  if v_gain > 0 and v_owner_balance < 0 then
    v_tax := round((v_gain * public.clown_tax_rate(v_owner_balance))::numeric,1);
    v_owner_net := v_gain - v_tax;
    update public.tax_bucket set amount = round((coalesce(amount,0) + v_tax)::numeric,1) where id = 1;
  end if;

  v_new_owner := public.apply_aura_delta_internal(
    v_owner, v_owner_net, 'post_vote',
    case when p_value > 0 then '+' else '' end || p_value::text || ' vote on your post'
  );

  select count(*) into v_tag_count
  from public.post_tags where post_id = p_post_id and tagged_user_id <> v_owner;

  if v_tag_count > 0 and v_gain <> 0 then
    v_tag_delta := round(((v_gain * 0.50) / v_tag_count)::numeric,1);
    for v_tag in
      select tagged_user_id from public.post_tags
      where post_id = p_post_id and tagged_user_id <> v_owner
    loop
      select aura into v_tag_balance from public.profiles where id = v_tag.tagged_user_id for update;
      v_tag_tax := 0;
      if v_tag_delta > 0 and v_tag_balance < 0 then
        v_tag_tax := round((v_tag_delta * public.clown_tax_rate(v_tag_balance))::numeric,1);
        update public.tax_bucket set amount = round((coalesce(amount,0) + v_tag_tax)::numeric,1) where id = 1;
      end if;
      perform public.apply_aura_delta_internal(
        v_tag.tagged_user_id,
        v_tag_delta - v_tag_tax,
        'tag_share',
        'Share from a tagged post vote'
      );
    end loop;
  end if;

  insert into public.vote_events(voter_id,target_user_id,post_id,source_type,old_value,new_value,delta)
  values(v_uid,v_owner,p_post_id,'post',v_old,p_value,v_gain);

  return jsonb_build_object(
    'ok', true,
    'post_delta', v_gain,
    'owner_aura', v_new_owner,
    'voter_aura', v_new_voter,
    'tax', v_tax
  );
end;
$$;

create or replace function public.cast_profile_vote(p_target_id uuid, p_value integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_old integer := 0;
  v_gain numeric;
  v_cost_delta numeric;
  v_target_balance numeric;
  v_tax numeric := 0;
  v_net numeric;
  v_new_target numeric;
  v_new_voter numeric;
  v_big_count integer;
begin
  if v_uid is null or not public.is_aura_member() then raise exception 'not authorized'; end if;
  if p_target_id = v_uid then raise exception 'cannot vote on yourself'; end if;
  if p_value not in (-50,-10,-5,-1,1,5,10,50) then raise exception 'invalid vote'; end if;
  if not exists(select 1 from public.profiles where id=p_target_id and is_member=true) then raise exception 'target not found'; end if;

  select value into v_old from public.profile_votes
  where voter_id=v_uid and target_id=p_target_id
  for update;
  if not found then v_old := 0; end if;
  if v_old = p_value then return jsonb_build_object('ok',true,'unchanged',true); end if;

  if abs(p_value)=50 then
    select count(*) into v_big_count from public.vote_events
    where voter_id=v_uid and target_user_id=p_target_id
      and abs(new_value)=50 and source_type in ('post','profile')
      and created_at > now() - interval '24 hours';
    if v_big_count >= 3 then
      v_new_voter := public.apply_aura_delta_internal(v_uid,-50,'anti_glaze','Too many ±50 votes to the same person in 24h');
      insert into public.vote_events(voter_id,target_user_id,source_type,old_value,new_value,delta)
      values(v_uid,p_target_id,'penalty',v_old,v_old,-50);
      return jsonb_build_object('ok',false,'reason','anti_glaze','penalty',-50,'voter_aura',v_new_voter);
    end if;
  end if;

  if v_old=0 then
    insert into public.profile_votes(voter_id,target_id,value) values(v_uid,p_target_id,p_value);
  else
    update public.profile_votes set value=p_value where voter_id=v_uid and target_id=p_target_id;
  end if;

  v_gain := p_value - v_old;
  v_cost_delta := public.vote_cost(p_value) - public.vote_cost(v_old);
  if v_cost_delta <> 0 then
    v_new_voter := public.apply_aura_delta_internal(v_uid,-v_cost_delta,'profile_vote_cost',
      case when v_cost_delta > 0 then 'Profile vote power cost' else 'Profile vote power refund' end);
  else
    select aura into v_new_voter from public.profiles where id=v_uid;
  end if;

  select aura into v_target_balance from public.profiles where id=p_target_id for update;
  v_net := v_gain;
  if v_gain > 0 and v_target_balance < 0 then
    v_tax := round((v_gain * public.clown_tax_rate(v_target_balance))::numeric,1);
    v_net := v_gain-v_tax;
    update public.tax_bucket set amount=round((coalesce(amount,0)+v_tax)::numeric,1) where id=1;
  end if;

  v_new_target := public.apply_aura_delta_internal(p_target_id,v_net,'profile_vote','Profile vote changed to '||p_value::text);

  insert into public.vote_events(voter_id,target_user_id,source_type,old_value,new_value,delta)
  values(v_uid,p_target_id,'profile',v_old,p_value,v_gain);

  return jsonb_build_object('ok',true,'target_aura',v_new_target,'voter_aura',v_new_voter,'tax',v_tax);
end;
$$;

create or replace function public.daily_checkin()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_last date;
  v_streak integer;
  v_balance numeric;
  v_reward numeric;
  v_new numeric;
begin
  if v_uid is null or not public.is_aura_member() then raise exception 'not authorized'; end if;
  select last_checkin, streak, aura into v_last, v_streak, v_balance
  from public.profiles where id=v_uid for update;

  if v_last = current_date then
    return jsonb_build_object('ok',false,'reason','already_checked_in');
  end if;

  if v_last = current_date - 1 then v_streak := coalesce(v_streak,0)+1; else v_streak := 1; end if;
  v_reward := case when v_balance < 0 then 7 else 5 end;
  v_new := public.apply_aura_delta_internal(v_uid,v_reward,'checkin',
    case when v_balance < 0 then 'Clown recovery check-in' else 'Daily check-in' end);

  update public.profiles set streak=v_streak,last_checkin=current_date where id=v_uid;
  return jsonb_build_object('ok',true,'aura',v_new,'streak',v_streak,'reward',v_reward);
end;
$$;

create or replace function public.manage_friend_request(p_target_id uuid, p_action text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.friendships%rowtype;
begin
  if v_uid is null or not public.is_aura_member() then raise exception 'not authorized'; end if;
  if p_target_id=v_uid then raise exception 'cannot friend yourself'; end if;
  if not exists(select 1 from public.profiles where id=p_target_id and is_member=true) then raise exception 'target not found'; end if;

  select * into v_row from public.friendships
  where least(requester_id,addressee_id)=least(v_uid,p_target_id)
    and greatest(requester_id,addressee_id)=greatest(v_uid,p_target_id)
  for update;

  if p_action='request' then
    if found then return jsonb_build_object('ok',true,'status',v_row.status); end if;
    insert into public.friendships(requester_id,addressee_id,status) values(v_uid,p_target_id,'pending') returning * into v_row;
    insert into public.notifications(user_id,actor_id,type,message)
      values(p_target_id,v_uid,'friend_request','sent you a friend request');
    return jsonb_build_object('ok',true,'status','pending');
  elsif p_action='accept' then
    if not found or v_row.status<>'pending' or v_row.addressee_id<>v_uid then raise exception 'no pending request'; end if;
    update public.friendships set status='accepted',updated_at=now() where id=v_row.id;
    insert into public.notifications(user_id,actor_id,type,message)
      values(v_row.requester_id,v_uid,'friend_accept','accepted your friend request');
    return jsonb_build_object('ok',true,'status','accepted');
  elsif p_action='remove' then
    if found then delete from public.friendships where id=v_row.id; end if;
    return jsonb_build_object('ok',true,'status','none');
  else
    raise exception 'invalid action';
  end if;
end;
$$;

create or replace function public.apply_inactivity_penalties_daily()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  r record;
begin
  for r in
    select id from public.profiles
    where is_member=true
      and last_checkin is not null
      and last_checkin < current_date - 1
      and (last_penalty_date is null or last_penalty_date < current_date)
  loop
    perform public.apply_aura_delta_internal(r.id,-2,'inactivity','Missed daily check-in');
    update public.profiles set streak=0,last_penalty_date=current_date where id=r.id;
  end loop;
end;
$$;

create or replace function public.settle_weekly_round()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_start timestamptz := date_trunc('week', now()) - interval '7 days';
  v_end timestamptz := date_trunc('week', now());
  v_post bigint;
  v_user uuid;
  v_pool numeric;
begin
  if exists(select 1 from public.weekly_rounds where starts_at=v_start and settled_at is not null) then return; end if;

  select id,user_id into v_post,v_user
  from public.posts
  where created_at >= v_start and created_at < v_end
  order by aura desc, created_at asc
  limit 1;

  select coalesce(amount,0) into v_pool from public.tax_bucket where id=1 for update;

  insert into public.weekly_rounds(starts_at,ends_at,winner_post_id,winner_user_id,pool_amount,settled_at)
  values(v_start,v_end,v_post,v_user,v_pool,now())
  on conflict do nothing;

  if v_user is not null and v_pool > 0 then
    perform public.apply_aura_delta_internal(v_user,v_pool,'weekly_prize','Weekly top post prize');
  end if;
  update public.tax_bucket set amount=0,last_reset=current_date where id=1;
end;
$$;

grant execute on function public.cast_post_vote(bigint,integer) to authenticated;
grant execute on function public.cast_profile_vote(uuid,integer) to authenticated;
grant execute on function public.daily_checkin() to authenticated;
grant execute on function public.manage_friend_request(uuid,text) to authenticated;
grant execute on function public.is_aura_member() to authenticated;

-- Remove permissive legacy policies before installing member-only policies.
do $$
declare r record;
begin
  for r in
    select schemaname, tablename, policyname from pg_policies
    where schemaname='public'
      and tablename in ('profiles','posts','votes','profile_votes','comments','post_tags','aura_ledger','tax_bucket','friendships','notifications','push_subscriptions','vote_events','weekly_rounds')
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.votes enable row level security;
alter table public.profile_votes enable row level security;
alter table public.comments enable row level security;
alter table public.post_tags enable row level security;
alter table public.aura_ledger enable row level security;
alter table public.tax_bucket enable row level security;
alter table public.friendships enable row level security;
alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.vote_events enable row level security;
alter table public.weekly_rounds enable row level security;

create policy profiles_member_read on public.profiles for select to authenticated using (public.is_aura_member());
create policy profiles_self_update on public.profiles for update to authenticated using (id=auth.uid() and public.is_aura_member()) with check (id=auth.uid() and public.is_aura_member());

create policy posts_member_read on public.posts for select to authenticated using (public.is_aura_member());
create policy posts_self_insert on public.posts for insert to authenticated with check (user_id=auth.uid() and public.is_aura_member());
create policy posts_self_delete on public.posts for delete to authenticated using (user_id=auth.uid() and public.is_aura_member());

create policy votes_member_read on public.votes for select to authenticated using (public.is_aura_member());
create policy profile_votes_member_read on public.profile_votes for select to authenticated using (public.is_aura_member());

create policy comments_member_read on public.comments for select to authenticated using (public.is_aura_member());
create policy comments_self_insert on public.comments for insert to authenticated with check (user_id=auth.uid() and public.is_aura_member());
create policy comments_self_delete on public.comments for delete to authenticated using (user_id=auth.uid() and public.is_aura_member());

create policy tags_member_read on public.post_tags for select to authenticated using (public.is_aura_member());
create policy tags_owner_insert on public.post_tags for insert to authenticated with check (
  public.is_aura_member() and exists(select 1 from public.posts p where p.id=post_id and p.user_id=auth.uid())
);
create policy tags_owner_delete on public.post_tags for delete to authenticated using (
  public.is_aura_member() and exists(select 1 from public.posts p where p.id=post_id and p.user_id=auth.uid())
);

create policy ledger_self_read on public.aura_ledger for select to authenticated using (user_id=auth.uid() and public.is_aura_member());
create policy tax_member_read on public.tax_bucket for select to authenticated using (public.is_aura_member());
create policy friendships_participant_read on public.friendships for select to authenticated using (
  public.is_aura_member() and (requester_id=auth.uid() or addressee_id=auth.uid())
);
create policy notifications_self_read on public.notifications for select to authenticated using (user_id=auth.uid() and public.is_aura_member());
create policy notifications_self_update on public.notifications for update to authenticated using (user_id=auth.uid() and public.is_aura_member()) with check (user_id=auth.uid() and public.is_aura_member());
create policy push_self_read on public.push_subscriptions for select to authenticated using (user_id=auth.uid() and public.is_aura_member());
create policy push_self_insert on public.push_subscriptions for insert to authenticated with check (user_id=auth.uid() and public.is_aura_member());
create policy push_self_update on public.push_subscriptions for update to authenticated using (user_id=auth.uid() and public.is_aura_member()) with check (user_id=auth.uid() and public.is_aura_member());
create policy push_self_delete on public.push_subscriptions for delete to authenticated using (user_id=auth.uid() and public.is_aura_member());
create policy vote_events_member_read on public.vote_events for select to authenticated using (public.is_aura_member());
create policy rounds_member_read on public.weekly_rounds for select to authenticated using (public.is_aura_member());

revoke all on public.profiles, public.posts, public.votes, public.profile_votes, public.comments, public.post_tags, public.aura_ledger, public.tax_bucket, public.friendships, public.notifications, public.push_subscriptions, public.vote_events, public.weekly_rounds from anon;
revoke insert, update, delete on public.votes, public.profile_votes, public.aura_ledger, public.tax_bucket, public.vote_events, public.weekly_rounds, public.friendships from authenticated;
revoke insert on public.profiles from authenticated;
revoke update on public.posts from authenticated;
revoke update on public.profiles from authenticated;
grant update (bio,avatar_url,banner_url,notify_new_posts) on public.profiles to authenticated;
grant select on public.profiles,public.posts,public.votes,public.profile_votes,public.comments,public.post_tags,public.aura_ledger,public.tax_bucket,public.friendships,public.notifications,public.push_subscriptions,public.vote_events,public.weekly_rounds to authenticated;
grant insert,delete on public.posts to authenticated;
grant insert,delete on public.comments to authenticated;
grant insert,delete on public.post_tags to authenticated;
grant update (read_at) on public.notifications to authenticated;
grant insert,update,delete on public.push_subscriptions to authenticated;

alter view if exists public.post_comment_counts set (security_invoker = true);
revoke all on public.post_comment_counts from anon;
grant select on public.post_comment_counts to authenticated;

-- Schedule automatic penalties and Monday 00:00 UTC weekly settlement when pg_cron is available.
do $$
begin
  create extension if not exists pg_cron with schema extensions;
exception when others then
  raise notice 'pg_cron could not be enabled automatically; schedule the two functions in Supabase Cron manually.';
end $$;

do $$
begin
  if exists(select 1 from pg_extension where extname='pg_cron') then
    perform cron.unschedule(jobid) from cron.job where jobname in ('aura-daily-penalties','aura-weekly-settlement');
    perform cron.schedule('aura-daily-penalties','15 0 * * *','select public.apply_inactivity_penalties_daily();');
    perform cron.schedule('aura-weekly-settlement','0 0 * * 1','select public.settle_weekly_round();');
  end if;
exception when others then
  raise notice 'Cron scheduling skipped: %', sqlerrm;
end $$;

commit;
