-- Aura economy/security overhaul
-- Apply this migration in Supabase before deploying the matching app branch.

create extension if not exists pgcrypto;

-- Track the last inactivity penalty so repeated page loads cannot double-charge.
alter table public.profiles
  add column if not exists last_inactivity_penalty date;

-- Private membership is separate from authentication. Existing Aura users are grandfathered in.
create table if not exists public.private_members (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  invited_by uuid references public.profiles(id) on delete set null,
  joined_at timestamptz not null default now()
);

insert into public.private_members(user_id)
select id from public.profiles
on conflict (user_id) do nothing;

alter table public.private_members enable row level security;

create or replace function public.is_aura_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists(select 1 from public.private_members where user_id = auth.uid());
$$;
revoke all on function public.is_aura_member() from public, anon;
grant execute on function public.is_aura_member() to authenticated;

create or replace function public._require_aura_member()
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null or not exists(select 1 from public.private_members where user_id=v_uid) then
    raise exception 'Aura membership required';
  end if;
  return v_uid;
end;
$$;
revoke all on function public._require_aura_member() from public, anon, authenticated;

create policy "private member self read"
on public.private_members for select to authenticated
using (user_id = auth.uid());
grant select on public.private_members to authenticated;

-- Friend relationships.
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_unique
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));

-- Browser push subscriptions.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

-- Durable notification inbox + server-side dedupe for push fanout.
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null,
  post_id bigint references public.posts(id) on delete cascade,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  created_at timestamptz not null default now()
);

-- Immutable vote history enables anti-glazing rules.
create table if not exists public.vote_events (
  id bigint generated by default as identity primary key,
  voter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint references public.posts(id) on delete cascade,
  old_value integer not null default 0,
  new_value integer not null,
  delta integer not null,
  accepted boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists vote_events_glaze_idx
  on public.vote_events(voter_id, target_user_id, created_at desc);

-- Explicit weekly rounds make the bank actually settle.
create table if not exists public.weekly_rounds (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  winner_post_id bigint references public.posts(id) on delete set null,
  winner_user_id uuid references public.profiles(id) on delete set null,
  pool_amount double precision not null default 0,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  unique (starts_at, ends_at)
);

-- Prevent duplicate current votes.
create unique index if not exists votes_voter_post_unique on public.votes(voter_id, post_id);
create unique index if not exists profile_votes_voter_target_unique on public.profile_votes(voter_id, target_id);

alter table public.friendships enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_events enable row level security;
alter table public.vote_events enable row level security;
alter table public.weekly_rounds enable row level security;

drop policy if exists "friendships visible to participants" on public.friendships;
create policy "friendships visible to participants"
on public.friendships for select to authenticated
using (public.is_aura_member() and (auth.uid() = requester_id or auth.uid() = addressee_id));

drop policy if exists "push subscriptions owner select" on public.push_subscriptions;
create policy "push subscriptions owner select"
on public.push_subscriptions for select to authenticated
using (public.is_aura_member() and auth.uid() = user_id);

drop policy if exists "notifications owner select" on public.notifications;
create policy "notifications owner select"
on public.notifications for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "notifications owner update" on public.notifications;
create policy "notifications owner update"
on public.notifications for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "weekly rounds authenticated read" on public.weekly_rounds;
create policy "weekly rounds authenticated read"
on public.weekly_rounds for select to authenticated
using (public.is_aura_member());

grant select on public.profiles, public.posts, public.comments, public.post_tags to authenticated;
grant select on public.aura_ledger, public.votes, public.profile_votes, public.tax_bucket to authenticated;
grant select on public.friendships, public.notifications, public.weekly_rounds to authenticated;

-- Replace any legacy permissive policies on economy/content tables with explicit rules.
do $
declare
  r record;
begin
  for r in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('profiles','posts','comments','post_tags','votes','profile_votes','aura_ledger','tax_bucket')
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $;

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_tags enable row level security;
alter table public.votes enable row level security;
alter table public.profile_votes enable row level security;
alter table public.aura_ledger enable row level security;
alter table public.tax_bucket enable row level security;

create policy "profiles authenticated read" on public.profiles for select to authenticated using (true);
create policy "posts authenticated read" on public.posts for select to authenticated using (true);
create policy "comments authenticated read" on public.comments for select to authenticated using (true);
create policy "post tags authenticated read" on public.post_tags for select to authenticated using (true);
create policy "votes authenticated read" on public.votes for select to authenticated using (true);
create policy "profile votes authenticated read" on public.profile_votes for select to authenticated using (true);
create policy "ledger owner read" on public.aura_ledger for select to authenticated using (auth.uid() = user_id);
create policy "tax bucket authenticated read" on public.tax_bucket for select to authenticated using (true);

revoke insert, update, delete on public.profiles from authenticated;
revoke insert, update, delete on public.posts from authenticated;
revoke insert, update, delete on public.comments from authenticated;
revoke insert, update, delete on public.post_tags from authenticated;
revoke insert, update, delete on public.votes from authenticated;
revoke insert, update, delete on public.profile_votes from authenticated;
revoke insert, update, delete on public.aura_ledger from authenticated;
revoke insert, update, delete on public.tax_bucket from authenticated;

-- Profile creation is tied to Supabase Auth metadata rather than trusting a browser-supplied user id.
create or replace function public.handle_new_aura_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username text;
begin
  v_username := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1), 'user'), '\s+', '_', 'g'));
  insert into public.profiles(id, username, aura, aura_all_time, streak, created_at)
  values(new.id, v_username, 100, 100, 0, now())
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_aura on auth.users;
create trigger on_auth_user_created_aura
after insert on auth.users
for each row execute function public.handle_new_aura_user();

create or replace function public.update_my_profile(
  p_bio text default null,
  p_avatar_url text default null,
  p_banner_url text default null,
  p_field text default 'bio'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_field = 'bio' then
    update public.profiles set bio = left(coalesce(p_bio,''), 280) where id=v_uid;
  elsif p_field = 'avatar' then
    update public.profiles set avatar_url = p_avatar_url where id=v_uid;
  elsif p_field = 'banner' then
    update public.profiles set banner_url = p_banner_url where id=v_uid;
  else
    raise exception 'invalid field';
  end if;
end;
$$;
grant execute on function public.update_my_profile(text,text,text,text) to authenticated;

create or replace function public.create_post(
  p_text text,
  p_image_url text default null,
  p_tagged_ids uuid[] default '{}'::uuid[]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_post_id bigint;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if length(trim(coalesce(p_text,''))) = 0 then raise exception 'post text required'; end if;
  if length(p_text) > 2000 then raise exception 'post is too long'; end if;

  insert into public.posts(user_id,text,image_url,aura)
  values(v_uid,trim(p_text),p_image_url,0)
  returning id into v_post_id;

  insert into public.post_tags(post_id,tagged_user_id)
  select v_post_id, x
  from unnest(coalesce(p_tagged_ids,'{}'::uuid[])) x
  where x <> v_uid and exists(select 1 from public.profiles where id=x)
  on conflict do nothing;

  return v_post_id;
end;
$$;
grant execute on function public.create_post(text,text,uuid[]) to authenticated;

create or replace function public.create_comment(p_post_id bigint, p_text text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_comment_id bigint;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if length(trim(coalesce(p_text,''))) = 0 then raise exception 'comment text required'; end if;
  if length(p_text) > 1000 then raise exception 'comment is too long'; end if;
  if not exists(select 1 from public.posts where id=p_post_id) then raise exception 'post not found'; end if;

  insert into public.comments(post_id,user_id,text)
  values(p_post_id,v_uid,trim(p_text))
  returning id into v_comment_id;

  return v_comment_id;
end;
$$;
grant execute on function public.create_comment(bigint,text) to authenticated;

-- Internal helpers. Never grant these directly to app users.
create or replace function public._aura_vote_cost(v integer)
returns double precision
language sql
immutable
as $$
  select case v
    when 1 then 1
    when 5 then 2
    when 10 then 5
    when 50 then 20
    else 0
  end;
$$;

create or replace function public._apply_aura_delta(
  p_user_id uuid,
  p_delta double precision,
  p_type text,
  p_description text
)
returns double precision
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old double precision;
  v_new double precision;
  v_all_time double precision;
begin
  select aura, coalesce(aura_all_time, aura, 0)
  into v_old, v_all_time
  from public.profiles
  where id = p_user_id
  for update;

  if not found then
    raise exception 'profile not found';
  end if;

  v_new := round((coalesce(v_old, 0) + p_delta)::numeric, 1)::double precision;
  v_all_time := greatest(v_all_time, v_new);

  update public.profiles
  set aura = v_new,
      aura_all_time = v_all_time
  where id = p_user_id;

  insert into public.aura_ledger(user_id, amount, type, description, balance_after)
  values (
    p_user_id,
    round(p_delta::numeric, 1)::double precision,
    p_type,
    p_description,
    v_new
  );

  return v_new;
end;
$$;

create or replace function public._clown_tax_rate(p_aura double precision)
returns double precision
language sql
immutable
as $$
  select case
    when p_aura < -500 then 0.45
    when p_aura < -100 then 0.35
    when p_aura < 0 then 0.25
    else 0
  end;
$$;

create or replace function public._apply_income_with_clown_tax(
  p_user_id uuid,
  p_amount double precision,
  p_type text,
  p_description text
)
returns double precision
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance double precision;
  v_rate double precision;
  v_tax double precision := 0;
  v_net double precision := p_amount;
  v_bucket double precision;
begin
  select aura into v_balance
  from public.profiles
  where id = p_user_id
  for update;

  if p_amount > 0 and v_balance < 0 then
    v_rate := public._clown_tax_rate(v_balance);
    v_tax := round((p_amount * v_rate)::numeric, 1)::double precision;
    v_net := round((p_amount - v_tax)::numeric, 1)::double precision;

    select amount into v_bucket from public.tax_bucket where id = 1 for update;
    update public.tax_bucket
    set amount = round((coalesce(v_bucket, 0) + v_tax)::numeric, 1)::double precision
    where id = 1;
  end if;

  return public._apply_aura_delta(p_user_id, v_net, p_type, p_description);
end;
$$;

revoke all on function public._aura_vote_cost(integer) from public, anon, authenticated;
revoke all on function public._apply_aura_delta(uuid,double precision,text,text) from public, anon, authenticated;
revoke all on function public._clown_tax_rate(double precision) from public, anon, authenticated;
revoke all on function public._apply_income_with_clown_tax(uuid,double precision,text,text) from public, anon, authenticated;

-- Cast a post vote transactionally.
create or replace function public.cast_post_vote(p_post_id bigint, p_value integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_owner uuid;
  v_prev integer := 0;
  v_delta integer;
  v_old_cost double precision;
  v_new_cost double precision;
  v_cost_delta double precision;
  v_owner_gain double precision;
  v_big_count integer;
  v_tags uuid[];
  v_tag uuid;
  v_tag_share double precision;
  v_tag_count integer;
  v_post_aura double precision;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_value not in (-50,-10,-5,-1,1,5,10,50) then raise exception 'invalid vote'; end if;

  select user_id into v_owner
  from public.posts
  where id = p_post_id
  for update;

  if v_owner is null then raise exception 'post not found'; end if;
  if v_owner = v_uid then raise exception 'cannot vote on your own post'; end if;

  select value into v_prev
  from public.votes
  where voter_id = v_uid and post_id = p_post_id;
  v_prev := coalesce(v_prev, 0);

  if v_prev = p_value then
    return jsonb_build_object('status','unchanged');
  end if;

  -- Max 3 big votes to the same person per rolling 24h. The 4th attempt costs 50 aura.
  if abs(p_value) = 50 and abs(v_prev) <> 50 then
    select count(*) into v_big_count
    from public.vote_events
    where voter_id = v_uid
      and target_user_id = v_owner
      and accepted = true
      and abs(new_value) = 50
      and created_at > now() - interval '24 hours';

    if v_big_count >= 3 then
      perform public._apply_aura_delta(v_uid, -50, 'glazing_penalty', 'Too many big votes to the same person in 24h');
      insert into public.vote_events(voter_id,target_user_id,post_id,old_value,new_value,delta,accepted)
      values (v_uid,v_owner,p_post_id,v_prev,p_value,p_value-v_prev,false);
      return jsonb_build_object('status','glazing_penalty','penalty',50);
    end if;
  end if;

  insert into public.votes(voter_id, post_id, value)
  values (v_uid, p_post_id, p_value)
  on conflict (voter_id, post_id)
  do update set value = excluded.value;

  v_delta := p_value - v_prev;

  update public.posts
  set aura = round((coalesce(aura,0) + v_delta)::numeric, 1)::double precision
  where id = p_post_id
  returning aura into v_post_aura;

  v_old_cost := case when v_prev > 0 then public._aura_vote_cost(v_prev) else 0 end;
  v_new_cost := case when p_value > 0 then public._aura_vote_cost(p_value) else 0 end;
  v_cost_delta := v_new_cost - v_old_cost;

  if v_cost_delta <> 0 then
    perform public._apply_aura_delta(
      v_uid,
      -v_cost_delta,
      case when v_cost_delta > 0 then 'vote_cost' else 'vote_refund' end,
      case when v_cost_delta > 0
        then 'Cost to send +' || p_value || ' vote'
        else 'Vote cost refund'
      end
    );
  end if;

  v_owner_gain := v_delta;
  if v_owner_gain <> 0 then
    perform public._apply_income_with_clown_tax(
      v_owner,
      v_owner_gain,
      'post_vote',
      case when v_delta > 0 then '+' else '' end || v_delta || ' change on your post'
    );
  end if;

  select array_agg(tagged_user_id)
  into v_tags
  from public.post_tags
  where post_id = p_post_id and tagged_user_id <> v_owner;

  v_tag_count := coalesce(array_length(v_tags, 1), 0);
  if v_tag_count > 0 and v_delta <> 0 then
    -- The total tag bonus is capped at 50% and split across all tagged users.
    v_tag_share := round(((v_delta * 0.5) / v_tag_count)::numeric, 1)::double precision;
    foreach v_tag in array v_tags loop
      if v_tag_share <> 0 then
        perform public._apply_income_with_clown_tax(
          v_tag,
          v_tag_share,
          'tag_share',
          'Share from a tagged post vote'
        );
      end if;
    end loop;
  end if;

  insert into public.vote_events(voter_id,target_user_id,post_id,old_value,new_value,delta,accepted)
  values (v_uid,v_owner,p_post_id,v_prev,p_value,v_delta,true);

  return jsonb_build_object(
    'status','ok',
    'post_aura',v_post_aura,
    'delta',v_delta,
    'vote_cost_delta',v_cost_delta
  );
end;
$$;
grant execute on function public.cast_post_vote(bigint,integer) to authenticated;

-- Profile votes are intentionally smaller and use the same atomic ledger.
create or replace function public.cast_profile_vote(p_target_id uuid, p_value integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_prev integer := 0;
  v_delta integer;
  v_old_cost double precision;
  v_new_cost double precision;
  v_cost_delta double precision;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_target_id = v_uid then raise exception 'cannot vote on yourself'; end if;
  if p_value not in (-10,-5,-1,1,5,10) then raise exception 'invalid profile vote'; end if;

  select value into v_prev
  from public.profile_votes
  where voter_id = v_uid and target_id = p_target_id;
  v_prev := coalesce(v_prev, 0);

  if v_prev = p_value then return jsonb_build_object('status','unchanged'); end if;

  insert into public.profile_votes(voter_id,target_id,value)
  values (v_uid,p_target_id,p_value)
  on conflict (voter_id,target_id)
  do update set value = excluded.value;

  v_delta := p_value - v_prev;
  v_old_cost := case when v_prev > 0 then public._aura_vote_cost(v_prev) else 0 end;
  v_new_cost := case when p_value > 0 then public._aura_vote_cost(p_value) else 0 end;
  v_cost_delta := v_new_cost - v_old_cost;

  if v_cost_delta <> 0 then
    perform public._apply_aura_delta(v_uid,-v_cost_delta,
      case when v_cost_delta > 0 then 'profile_vote_cost' else 'profile_vote_refund' end,
      'Profile vote cost adjustment');
  end if;

  perform public._apply_income_with_clown_tax(
    p_target_id,
    v_delta,
    'profile_vote',
    'Profile vote changed by ' || v_delta
  );

  return jsonb_build_object('status','ok','delta',v_delta,'vote_cost_delta',v_cost_delta);
end;
$$;
grant execute on function public.cast_profile_vote(uuid,integer) to authenticated;

create or replace function public.daily_checkin()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_last date;
  v_streak integer;
  v_new_streak integer;
  v_balance double precision;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;

  select last_checkin, streak into v_last, v_streak
  from public.profiles
  where id = v_uid
  for update;

  if v_last = current_date then
    return jsonb_build_object('status','already');
  end if;

  v_new_streak := case when v_last = current_date - 1 then coalesce(v_streak,0) + 1 else 1 end;
  v_balance := public._apply_aura_delta(v_uid,5,'checkin','Day ' || v_new_streak || ' check-in');

  update public.profiles
  set streak = v_new_streak,
      last_checkin = current_date,
      last_inactivity_penalty = current_date
  where id = v_uid;

  return jsonb_build_object('status','ok','streak',v_new_streak,'aura',v_balance);
end;
$$;
grant execute on function public.daily_checkin() to authenticated;

create or replace function public.sync_inactivity_penalty()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_last_checkin date;
  v_last_penalty date;
  v_anchor date;
  v_days integer;
  v_penalty integer;
  v_balance double precision;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;

  select last_checkin, last_inactivity_penalty
  into v_last_checkin, v_last_penalty
  from public.profiles
  where id = v_uid
  for update;

  if v_last_checkin is null then
    update public.profiles set last_inactivity_penalty = current_date where id = v_uid;
    return jsonb_build_object('status','none');
  end if;

  v_anchor := greatest(v_last_checkin, coalesce(v_last_penalty, v_last_checkin));
  v_days := greatest((current_date - v_anchor) - 1, 0);

  if v_days <= 0 then return jsonb_build_object('status','none'); end if;

  v_penalty := least(v_days * 2, 20);
  v_balance := public._apply_aura_delta(v_uid,-v_penalty,'inactivity','Missed ' || v_days || ' days — streak reset');

  update public.profiles
  set streak = 0,
      last_inactivity_penalty = current_date - 1
  where id = v_uid;

  return jsonb_build_object('status','penalty','penalty',v_penalty,'aura',v_balance);
end;
$$;
grant execute on function public.sync_inactivity_penalty() to authenticated;

create or replace function public.apply_daily_inactivity_penalties()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r record;
  v_anchor date;
  v_days integer;
  v_penalty integer;
  v_count integer := 0;
  v_total double precision := 0;
begin
  for r in
    select id, last_checkin, last_inactivity_penalty
    from public.profiles
    where last_checkin is not null
    order by id
  loop
    v_anchor := greatest(r.last_checkin, coalesce(r.last_inactivity_penalty, r.last_checkin));
    v_days := greatest((current_date - v_anchor) - 1, 0);
    if v_days > 0 then
      v_penalty := least(v_days * 2, 20);
      perform public._apply_aura_delta(
        r.id,
        -v_penalty,
        'inactivity',
        'Missed ' || v_days || ' days — streak reset'
      );
      update public.profiles
      set streak = 0,
          last_inactivity_penalty = current_date - 1
      where id = r.id;
      v_count := v_count + 1;
      v_total := v_total + v_penalty;
    end if;
  end loop;

  return jsonb_build_object('status','ok','users_penalized',v_count,'aura_removed',v_total);
end;
$$;
revoke all on function public.apply_daily_inactivity_penalties() from public, anon, authenticated;
grant execute on function public.apply_daily_inactivity_penalties() to service_role;

-- Friendship RPCs.
create or replace function public.send_friend_request(p_target_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_row public.friendships%rowtype;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_target_id = v_uid then raise exception 'cannot friend yourself'; end if;

  select * into v_row
  from public.friendships
  where least(requester_id,addressee_id)=least(v_uid,p_target_id)
    and greatest(requester_id,addressee_id)=greatest(v_uid,p_target_id)
  for update;

  if found then
    if v_row.status = 'pending' and v_row.addressee_id = v_uid then
      update public.friendships set status='accepted', updated_at=now() where id=v_row.id;
      return jsonb_build_object('status','accepted','id',v_row.id);
    end if;
    return jsonb_build_object('status',v_row.status,'id',v_row.id);
  end if;

  insert into public.friendships(requester_id,addressee_id,status)
  values (v_uid,p_target_id,'pending')
  returning * into v_row;

  return jsonb_build_object('status','pending','id',v_row.id);
end;
$$;
grant execute on function public.send_friend_request(uuid) to authenticated;

create or replace function public.respond_friend_request(p_friendship_id bigint, p_accept boolean)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
  v_status text;
begin
  if v_uid is null then raise exception 'not authenticated'; end if;

  update public.friendships
  set status = case when p_accept then 'accepted' else 'declined' end,
      updated_at = now()
  where id = p_friendship_id
    and addressee_id = v_uid
    and status = 'pending'
  returning status into v_status;

  if v_status is null then raise exception 'request not found'; end if;
  return jsonb_build_object('status',v_status);
end;
$$;
grant execute on function public.respond_friend_request(bigint,boolean) to authenticated;

create or replace function public.remove_friend(p_friendship_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := public._require_aura_member();
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  delete from public.friendships
  where id=p_friendship_id and (requester_id=v_uid or addressee_id=v_uid);
end;
$$;
grant execute on function public.remove_friend(bigint) to authenticated;

-- Weekly settlement. Intended to be invoked by the authenticated server cron route.
create or replace function public.settle_weekly_pool()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_end timestamptz := date_trunc('day', now()) - (extract(dow from now())::int * interval '1 day');
  v_start timestamptz := v_end - interval '7 days';
  v_existing bigint;
  v_post_id bigint;
  v_user_id uuid;
  v_pool double precision;
begin
  select id into v_existing from public.weekly_rounds
  where starts_at=v_start and ends_at=v_end and settled_at is not null;

  if v_existing is not null then return jsonb_build_object('status','already_settled'); end if;

  select id,user_id into v_post_id,v_user_id
  from public.posts
  where created_at >= v_start and created_at < v_end
  order by aura desc, created_at asc
  limit 1;

  select coalesce(amount,0) into v_pool from public.tax_bucket where id=1 for update;

  insert into public.weekly_rounds(starts_at,ends_at,winner_post_id,winner_user_id,pool_amount,settled_at)
  values(v_start,v_end,v_post_id,v_user_id,v_pool,now())
  on conflict (starts_at,ends_at)
  do update set winner_post_id=excluded.winner_post_id,winner_user_id=excluded.winner_user_id,
    pool_amount=excluded.pool_amount,settled_at=excluded.settled_at;

  if v_user_id is not null and v_pool > 0 then
    perform public._apply_aura_delta(v_user_id,v_pool,'weekly_prize','Weekly top-post prize');
  end if;

  update public.tax_bucket set amount=0, last_reset=current_date where id=1;

  return jsonb_build_object('status','ok','winner_user_id',v_user_id,'winner_post_id',v_post_id,'pool',v_pool);
end;
$$;
revoke all on function public.settle_weekly_pool() from public, anon, authenticated;
grant execute on function public.settle_weekly_pool() to service_role;

-- Repair the existing ledger without rewriting balances: add a reconciliation row only when needed.
with latest as (
  select distinct on (user_id) user_id, balance_after
  from public.aura_ledger
  order by user_id, created_at desc, id desc
)
insert into public.aura_ledger(user_id,amount,type,description,balance_after)
select p.id,
       round((p.aura - coalesce(l.balance_after,0))::numeric,1)::double precision,
       'reconciliation',
       case when l.user_id is null then 'Ledger starting balance after economy migration'
            else 'Ledger reconciliation after economy migration' end,
       p.aura
from public.profiles p
left join latest l on l.user_id=p.id
where l.user_id is null or abs(p.aura - l.balance_after) > 0.0001;
